SELECT A.NAME,
       CASE
           WHEN A.BOSS IS NULL
               THEN 'CEO'
           WHEN B.BOSS IS NOT NULL
               THEN 'MANAGER'
           ELSE 'WORKER'
           END AS BOSS
FROM EMPLOYEE_RELATIONSHIPS A
         LEFT OUTER JOIN (SELECT DISTINCT BOSS FROM EMPLOYEE_RELATIONSHIPS) B ON A.NAME = B.BOSS;

